USE [master]
GO

/****** Object:  Database [dbColeRegistro]    Script Date: 9/4/2020 7:05:49 PM ******/
CREATE DATABASE [dbColeRegistro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbColeRegistro', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbColeRegistro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbColeRegistro_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbColeRegistro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbColeRegistro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbColeRegistro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbColeRegistro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbColeRegistro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbColeRegistro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbColeRegistro] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbColeRegistro] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [dbColeRegistro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbColeRegistro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbColeRegistro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbColeRegistro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbColeRegistro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbColeRegistro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbColeRegistro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbColeRegistro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbColeRegistro] SET  ENABLE_BROKER 
GO

ALTER DATABASE [dbColeRegistro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbColeRegistro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbColeRegistro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbColeRegistro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbColeRegistro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbColeRegistro] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbColeRegistro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbColeRegistro] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbColeRegistro] SET  MULTI_USER 
GO

ALTER DATABASE [dbColeRegistro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbColeRegistro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbColeRegistro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbColeRegistro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbColeRegistro] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbColeRegistro] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbColeRegistro] SET  READ_WRITE 
GO

